/*
 * routeBase.inc
 *
 *  Created on: 2016年8月15日
 *      Author: chenzifeng
 */

#ifndef INCLUDE_ROUTEBASE_H_
#define INCLUDE_ROUTEBASE_H_

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <netdb.h>
#include <fcntl.h>
#include <string.h>
#include <time.h>
#include <sys/socket.h>
#include <sys/epoll.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#include "routeServer.h"
#include "routeClient.h"
#include "routeConfig.h"
#include "routeAllot.h"

#endif /* ROUTECLIENT_H_ */